### ISSUE TITLE
run on turtlebot2

### ISSUE THREAD

**Issue by asialulu** [Shuijing725/CrowdNav_DSRNN#13]
hi, 
   I'm very interested in experiments on robots. What do I need to do to run on robots? 
Thank you!

**Comment by Shuijing725** [comment]
Hi asialulu,

There are several pieces that are needed to fill the sim2real gap:
1. Use sensors to detect the positions of people;
2. Track the ID of each detected person so that they are in a consistent order, and feed the positions of tracked people into the observation of the RL network;
3. Use a more realistic robot dynamics, such as unicycle (set `action_space.kinematics = "holonomic"` in `config.py`). However, the true dynamics depend on the robot you are using.

Hope it helps!

**Comment by Shuijing725** [comment]
@asialulu The sim2real tutorial is released here: https://github.com/Shuijing725/CrowdNav_Sim2Real_Turtlebot
