### ISSUE TITLE
Can I know how did you transfer the policy learned in the simulator to a real-world TurtleBot 2i/ 3???

### ISSUE THREAD

**Issue by sumedhreddy90** [Shuijing725/CrowdNav_DSRNN#14]

**Comment by Mirorrn** [comment]
I would be also interested

**Comment by Shuijing725** [comment]
Hi all,

For sim2real, you'll need a people detector and tracker to obtain the (x, y) positions of humans. The choice of detector and tracker depends on the sensors (camera, lidar, etc). 
In addition, we also used a more realistic robot dynamics (unicycle with noises), and tried to reduce the gap between the behaviors of simulated people and real people. 

I will consider releasing sim2real code for my next paper on crowd navigation, since quite a few people are interested. But I apologize that I don't have a specific date on when this will happen. 

Follow-up questions are welcome if you have any.

**Comment by Shuijing725** [comment]
@sumedhreddy90 @Mirorrn The sim2real tutorial is released here: https://github.com/Shuijing725/CrowdNav_Sim2Real_Turtlebot
