### ISSUE TITLE
Is it possible to use multiple robot?

### ISSUE THREAD

**Issue by grlinnn** [Shuijing725/CrowdNav_DSRNN#22]
Hi!

I'm still super new to Reinforcement Learning.

I want to know if it is possible to train multiple robots instead of just one like your code applied?

Thankyou!

**Comment by Shuijing725** [comment]
There are many ways to do this, I'll just share my thoughts.

- If you assume all robots share the same RL policy, then you just need to change the gym environment: we have to calculate the observation for all robots in [the `generate_ob` function](https://github.com/Shuijing725/CrowdNav_DSRNN/blob/c2d8148fb86be46535e906e4a725c30ceaa1c550/crowd_sim/envs/crowd_sim_dict.py#L45), and use the same network to output all actions, which are applied to all robots in [the `step` function.](https://github.com/Shuijing725/CrowdNav_DSRNN/blob/c2d8148fb86be46535e906e4a725c30ceaa1c550/crowd_sim/envs/crowd_sim_dict.py#L118)
- If you assume each robot has its own policy, then we need to apply the environment changes above, plus instantiate as many networks as you need, and train all of them instead of just one.

**Comment by grlinnn** [comment]
I'm honestly still not quite clear about _how to add **n** more robots_.

Can you tell me where exactly I can add more robot instances?

I was exploring the code for a while, and had a rough guess that I need add more Robot instances in `crowd_sim/envs/crowd_sim.py` such applied at `self.robot2 = None` and follow the other first robot's config.

Thank you.

**Comment by Shuijing725** [comment]
I agree about your idea of adding more robot instances in the gym environment. For the additional robots, you can follow the code of the first robot. The only difference (I think) is that each robot has different observations, dynamics, and actions.

**Comment by grlinnn** [comment]
Hi!

Recently I have tried to deal with this problem. I have adding one more robot instances in `crowd_sim/envs/crowd_sim.py` and `crowd_sim/envs/crowd_sim_dict.py`. I have done something like : 

```
# set robot for this envs
        rob_RL = Robot(config, 'robot')
        rob2_RL = Robot(config,'robot2')
        self.set_robot(rob_RL)
        self.set_robot(rob2_RL)
```

Is this the correct way to do it? Since I am still having bugs although I have followed the first robot's code.

Sorry for bothering you, I am still curious about this thing.

Thankyou!

**Comment by Shuijing725** [comment]
Hi @grlinnn,

Based on what you provided, I think your implementation looks good. A minor problem is that `set_robot` function will also set the observation space of the environment, which is done twice and a little redundant. But I don't think it will cause a big issue, as long as you set both `robot_RL` and `robot2_RL` as `self.robot` and `self.robot2`.

**Comment by grlinnn** [comment]
Hi!

Sorry to bother you again.

I want to ask you if you have any idea on my recent problem that I can't overcome.

`action = self.robot.policy.clip_action(action, self.robot.v_pref)`

After I had some updates like I mentioned earlier in this post, the following problem occurred and I had no idea what's going on.

`AttributeError: 'ORCA' object has no attribute 'clip_action'`

Do you have any idea what probably cause this problem?

Thankyou!

**Comment by Shuijing725** [comment]
It's probably because you set the `self.robot.policy` to ORCA, but `clip_action` function is only implemented for "srnn" policy. Please see the files in [crowd_nav/policy](https://github.com/Shuijing725/CrowdNav_DSRNN/tree/main/crowd_nav/policy) for reference.

**Comment by Shuijing725** [comment]
I think the attribute error you mentioned last week is only related to the second policy you just mentioned in `config.py`
