### ISSUE TITLE
train

### ISSUE THREAD

**Issue by cir-lab** [Shuijing725/CrowdNav_DSRNN#4]

**Comment by cir-lab** [comment]
Hello, I am very sorry to disturb you.  I noticed you said the environment configurations file is  crowd_nav/configs/env.config，but I can‘t find this file.
![image](https://user-images.githubusercontent.com/82627287/120135682-5fa0db80-c203-11eb-88b8-748813e0551b.png)

**Comment by Shuijing725** [comment]
Sorry, it should be `crowd_nav/configs/config.py`. The readme is updated now.

**Comment by cir-lab** [comment]
I am very sorry to disturb you again. When I run the program python test.py, I  encountered problem “ **'GRU' object has no attribute 'proj_size'** ”
![image](https://user-images.githubusercontent.com/82627287/120165256-f5516080-c22d-11eb-98b5-4da27a57a6b8.png)

**Comment by Shuijing725** [comment]
It will be easier if you could show the full error message.

**Comment by cir-lab** [comment]
![image](https://user-images.githubusercontent.com/82627287/120254087-989c8700-c2bb-11eb-829f-ed73048eae67.png)
The full error message is shown in the figure.
I would be very grateful if you can help me find the problem.

**Comment by Shuijing725** [comment]
It looks like the error is caused by PyTorch data parallelism, see https://discuss.pytorch.org/t/issues-using-data-parallelism-dataparallel-object-has-no-attribute-xxxxxxxx/94102.
If you only have one gpu, can you try to replace `nn.DataParallel(actor_critic).to(device)` with `actor_critic.to(device)`? If you need to train it on multiple gpus, can you try to replace it with `nn.DataParallel(actor_critic).module.to(device)`?

**Comment by mincheulkim** [comment]
It might be caused by using different version of pyTorch and torchvision. 
What about using below version of software?

torch==1.7.1
torchvision==0.1.8

**Comment by Shuijing725** [comment]
Good catch @mincheulkim ! Previously I used PyTorch 1.5.0. If you want to load the example model, this repo supports up to PyTorch 1.7.1. The `requirements.txt` is updated.
